### ISSUE TITLE
您好,docker-compose 环境中遵循文档3.1如果热更新 ,设置成watch后backend up不起来直接报错

### ISSUE THREAD

**Issue by bo1839** [mochat-cloud/docker-compose#3]
报错如下
Fatal error: Uncaught RuntimeException: The class reflector object does not init yet in /opt/www/vendor/hyperf/di/src/BetterReflectionManager.php:39
backend        | Stack trace:
backend        | #0 /opt/www/vendor/hyperf/di/src/BetterReflectionManager.php(62): Hyperf\Di\BetterReflectionManager::getClassReflector()
backend        | #1 /opt/www/vendor/hyperf/di/src/Aop/PropertyHandlerVisitor.php(90): Hyperf\Di\BetterReflectionManager::reflectClass()
backend        | #2 /opt/www/vendor/hyperf/di/src/Aop/PropertyHandlerVisitor.php(64): Hyperf\Di\Aop\PropertyHandlerVisitor->buildConstructor()
backend        | #3 /opt/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(230): Hyperf\Di\Aop\PropertyHandlerVisitor->leaveNode()
backend        | #4 /opt/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
backend        | #5 /opt/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
backend        | #6 /opt/www/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray()
backend        | #7 /opt/www/vendor/hyperf/di/src/Aop/Ast.p in /opt/www/vendor/hyperf/di/src/BetterReflectionManager.php on line 39
backend        | Stop server success.

**Comment by maxincai** [comment]
更新再试试
